project_id = "euhevsyahruqehiqgway"

[functions.midjourney-generate]
verify_jwt = false

[functions.generate-coloring-page]
verify_jwt = false

[functions.process-generation-job]
verify_jwt = false
 
 [functions.export-book-zip]
 verify_jwt = false
